### PR TITLE
fixed search query bug + organized components

### PR DESCRIPTION
**Pull request by Ashwin087**
- Fixed issue of subsequent searches not working.
- Organized components in folder

### CODE REVIEW

**Comment by Ashwin087** [comment]
Review y'all. We are a TEAM. GO TEAM GO!

**Review by Edjrich — APPROVED** [review]
😎

**Comment by shaun-seeram** [comment]
I aproof

**Review by shaun-seeram — APPROVED** [review]
Poop. 🐛

**Pull request merged**
